name: Issues Workflow

on:
    issues:
         types: [opened, edited, reopened]
jobs:
    issue:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Run issue script
              run: |
                echo "Issue event triggered"
                echo "Issue title: ${{ github.event.issue.title }}"
                echo "Issue body: ${{ github.event.issue.body }}"
                echo "Issue number: ${{ github.event.issue.number }}"